### ISSUE TITLE
Redo authentication struct / enums to be consistent with trino configuration

### ISSUE THREAD

**Issue by maltesander** [stackabletech/trino-operator#307]
Currently we set up Trino authentication for PASSWORD via file like:
```
  authentication:
    method:
      multiUser:
        userCredentialsSecret:
          name: simple-trino-users-secret
```
and ldap (currently in https://github.com/stackabletech/trino-operator/pull/306):
```
  authentication:
    method:
      ldap:
        authenticationClass: ldap-with-tls
```
The `method` part is represented as enum. This does not allow us to support multiple authentication types.

We propose a `BREAKING` change for this like:
```
  authentication:
    password:
      file:
        userCredentialsSecret:
          name: simple-trino-users-secret
      ldap:
        authenticationClass: ldap-with-tls
      oauth2:
        blabla....
```
This is breaking but closer to the Trino configuration and allows us to enable multiple authentication methods.
