### ISSUE TITLE
Support Delta connector

### ISSUE THREAD

**Issue by ruslanguns** [stackabletech/trino-operator#538]
Docs: https://trino.io/docs/current/connector/delta-lake.html

I was able to setup a delta connector with the following workaround 👇🏻 :

1. Established a TrinoCatalog using Hive as the connector to add S3 connection capabilities, necessary for accessing Delta tables stored in S3.

```yaml
apiVersion: trino.stackable.tech/v1alpha1
kind: TrinoCatalog
metadata:
  name: hive
  namespace: infrastructure
  labels:
    trino: trino
spec:
  connector:
    hive:
      metastore:
        configMap: hive
      s3:
        reference: spark-s3-connection
  configOverrides:
    hive.metastore.username: delta
```
> This allows me to add the s3 connection capabilities.

2. Configured a ConfigMap named trino-delta-properties with settings for the Delta connector. This configuration mirrors the Hive setup but excludes hive.security=allow-all due to compatibility issues. It also introduces a Delta-specific setting to enable table registration from S3 storage.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-delta-properties
  namespace: infrastructure
data:
  delta.properties: |
    connector.name=delta_lake
    hive.metastore.uri=thrift://hive.default.svc.cluster.local:9083
    hive.metastore.username=delta
    hive.s3.aws-access-key=${ENV:CATALOG_HIVE_HIVE_S3_AWS_ACCESS_KEY}
    hive.s3.aws-secret-key=${ENV:CATALOG_HIVE_HIVE_S3_AWS_SECRET_KEY}
    hive.s3.endpoint=http://s3
    hive.s3.path-style-access=true
    hive.s3.ssl.enabled=false
    delta.register-table-procedure.enabled=true
```

> this configuration has an additional parameter ` delta.register-table-procedure.enabled=true` as it'srequired in order to register delta tables that are already in the s3 object storage.

3. Adjusted `podOverrides` for both worker and coordinator to mount the `ConfigMap`. However, this method replaces the entire `/stackable/config/catalog` directory, inadvertently removing the `hive.properties` file generated by `TrinoCatalog`. While sufficient for some scenarios, this approach may not cater to all use cases due to its overriding behavior.

> Alternatively use `initContainers` to inject the Delta connector properties into the existing configuration directory without overwriting existing configurations.

```yaml
podOverrides:
     spec:
        containers:
        - name: trino
           volumeMounts:
           - name: delta-properties
             mountPath: /stackable/config/catalog
        volumes:
        - name: access-control-properties
          configMap:
          - name: delta-properties
             configMap:
               name: trino-delta-properties
    roleGroups:
      default:
        replicas: 1
```
